# Generated by Django 6.0.8 on 2026-08-20 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['created_at']},
        ),
    ]
