# Generated by Django 6.0.8 on 2026-08-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('ORDER_CONFIRMATION', 'Order Confirmation'), ('LOW_STOCK_ALERT', 'Low Stock Alert'), ('DAILY_STOCK_REPORT', 'Daily Stock Report')], max_length=50),
        ),
    ]
