# Generated by Django 6.0.8 on 2026-08-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notificationlog_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('ORDER_CONFIRMATION', 'Order Confirmation'), ('LOW_STOCK_ALERT', 'Low Stock Alert'), ('DAILY_STOCK_REPORT', 'Daily Stock Report'), ('SALE_CAMPAIGN', 'Sale Campaign')], max_length=50),
        ),
    ]
